drop trigger if exists audit_deals on deals;
drop trigger if exists audit_contacts on contacts;
drop trigger if exists audit_organizations on organizations;
drop trigger if exists audit_leads on leads;
drop trigger if exists audit_activities on activities;
drop trigger if exists audit_notes on notes;
drop trigger if exists audit_proposals on proposals;
drop trigger if exists audit_attachments on attachments;
drop trigger if exists audit_pipelines on pipelines;
drop trigger if exists audit_pipeline_stages on pipeline_stages;
drop trigger if exists audit_lost_reasons on lost_reasons;
drop trigger if exists audit_custom_fields on custom_fields;
drop trigger if exists audit_automation_rules on automation_rules;
drop trigger if exists audit_teams on teams;
drop trigger if exists audit_profiles on profiles;
drop function if exists public.audit_log_trigger();
drop function if exists public.audit_value(text, jsonb);
drop function if exists public.audit_resolve_ref(text, text);
drop table if exists audit_logs;
